export default {
    THEME_CHANGE:"THEME_CHANGE",
    THEME_INIT:"THEME_INIT",

    // 最热模块设计
    POPULAR_FRESH:'POPULAR_FRESH',
    POPULAR_SUCCESS:'POPULAR_SUCCESS',
    POPULAR_ERROR:'POPULAR_ERROR',

}