export default {
    THEME_CHANGE:"THEME_CHANGE",
    THEME_INIT:"THEME_INIT",

    // 最热模块设计
    // 下拉刷新
    POPULAR_FRESH:'POPULAR_FRESH',
    POPULAR_FRESH_SUCCESS:'POPULAR_FRESH_SUCCESS',
    POPULAR_FRESH_ERROR:'POPULAR_FRESH_ERROR',
    // 上啦加载更多
    // POPULAR_LOADMORE:'POPULAR_LOADMORE',
    POPULAR_LOADMORE_SUCCESS:'POPULAR_LOADMORE_SUCCESS',
    POPULAR_LOADMORE_ERROR:'POPULAR_LOADMORE_ERROR',


    // 趋势模块设计
    // 下拉刷新
    TRENDING_FRESH:'TRENDING_FRESH',
    TRENDING_FRESH_SUCCESS:'TRENDING_FRESH_SUCCESS',
    TRENDING_FRESH_ERROR:'TRENDING_FRESH_ERROR',
    // 上啦加载更多
    // POPULAR_LOADMORE:'POPULAR_LOADMORE',
    TRENDING_LOADMORE_SUCCESS:'TRENDING_LOADMORE_SUCCESS',
    TRENDING_LOADMORE_ERROR:'TRENDING_LOADMORE_ERROR',


    // 收藏模块设计
    COLLECT_FRESH:'COLLECT_FRESH',
    COLLECT_FRESH_SUCCESS:'COLLECT_FRESH_SUCCESS',
    COLLECT_FRESH_ERROR:'COLLECT_FRESH_ERROR',

    // 语言选择
    LANGUAGE_FRESH_SUCCESS:'LANGUAGE_FRESH_SUCCESS'
}